version: '2'

services:

### Code Box ###
    codebox:
        build:
            context: ./docker/codebox
            args:
                - INSTALL_DRUSH=false
                - INSTALL_RUNNER=false #enable this for sonar runner
                - PUID=1000
                - PGID=1000
        volumes_from:
            - volumes_source
        ports:
           - "22:22"
        tty: true

### PHP-FPM  ###

    php-fpm:
        build:
            context: ./docker/php-fpm/php56
#            context: ./docker/php-fpm/php7
        volumes_from:
            - volumes_source
        expose:
            - "9000"
        links:
            - codebox

#### Apache ###

    apache2:
        build:
            context: ./docker/apache2
            args:
                - PHP_SOCKET="php-fpm:9000"
                - WEB_DOCUMENT_ROOT="/var/www/"
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/apache2:/var/log/apache2
        ports:
            - "8080:80"
            - "443:443"
        links:
            - php-fpm

#### Nginx ####

    nginx:
        build:
            context: ./docker/nginx
            args:
                - PHP_UPSTREAM=php-fpm:9000
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "81:80"
            - "444:443"
        links:
            - php-fpm
### MySQL ###

    mysql:
        build:
            context: ./docker/mysql/5.7
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: test
            MYSQL_USER: maju
            MYSQL_PASSWORD: 1234maju
            MYSQL_ROOT_PASSWORD: 1234maju

### Sonarqube###

    sonarqube:
        build:
            context: ./docker/sonar
        ports:
            - "9000:9000"
        links:
            - mysql
        environment:
            - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
            - SONARQUBE_JDBC_USERNAME=maju
            - SONARQUBE_JDBC_PASSWORD=1234maju
        restart: always

    lamp:
        image: tianon/true
        depends_on:
            - php-fpm
            - apache2
            - mysql
#### Web source ###

    volumes_source:
        image: tianon/true
        volumes:
            - ../:/var/www/

###  Data source ###

    volumes_data:
        image: tianon/true
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./data/sessions:/sessions
            - ./data/sonarqube:/opt/sonarqube


    phpmyadmin:
        build:
            context: ./docker/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - 8181:80
        volumes_from:
            - volumes_data
        links:
            - mysql